<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // catch() 用来是定Promise失败的回调
        const p = new Promise((resolve, reject)=>{
            setTimeout(()=>{
                // 设置p 对象的状态为失败，并且设置失败的值
                reject("出错啦");
            },1000)
        });

        // p.then(function (value){},function (reason) {
        //     console.error(reason);    
        // });

        // 或者通过另外一种方法来指定
        p.catch(function(reason){
            console.warn(reason);
        });
        // then方法不指定第一个参数，结果就和catch一样
    </script>
</body>
</html>